### ISSUE TITLE
Successful gameplay and rating

### ISSUE THREAD

**Issue by MichaS01** [MichaS01/SFML-Key-Hunter#18]
We hope you liked the game and we deserved a nice one mark ;)

**Comment by JOtworowski** [comment]
Tomorrow we'll talk about the project evaluation. Do you plan to add running the game via .exe file or install via .msi package ?

**Comment by MichaS01** [comment]
I'm still trying to add running the game via .exe file, but it's not that simple and quic. 🙁🙁🙁

**Comment by JOtworowski** [comment]
Stworzona gra jest bardzo wciągająca. Grałem w nią dopóki nie udało mi się zdobyć wszystkich 3 kluczy. Bardzo dobrze zaanimowano bohatera. Przez te kilkanaście minut grania nie wystąpiły żadne problemy z kolizjami. Mechanika wymaga pewnej wprawy ale wydaje się dobrze przemyślana. Częściowo udało się zrealizować wymagania dotyczące polimorfizmu i alokacji pamięci poprzez wykorzystanie dekonstruktorów. Zarówno prowadzenie gita, wygenerowanie pliku .exe jak i wykorzystanie dziedziczenia klas spełnia wymagania. Tak jak mówiłem na zajęciach pewnym mankamentem jest ilość stworzonego kontentu. Brakuje mi trochę innych postaci lub obiektów interaktywnych.

Projekt oceniam na 87,5%. Jednak jednocześnie chciałbym jeszcze raz powtórzyć, że elementy które znalazły się w grze są bardzo dopracowane, a całość pod względem doboru grafik, tła i muzyki wygląda na spójną wizję
